import Head from 'next/head'
import Image from 'next/image'

import { useState } from 'react';

import styles from '../styles/Home.module.css'

export default function Home() {
  const [sampleInput, setSampleInput] = useState('')
  const [result, setResult] = useState('')

  async function onSubmit(event) {
    event.preventDefault()
    const response = await fetch(`/api/generate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
        body: JSON.stringify({ text: sampleInput }),
      });
      const data = await response.json();
      setResult(data.result)
      setSampleInput("");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"></link>

      </Head>

      <main className={styles.main}>
        {/* <Image src="/images/hero.jpg" alt="hero" width={1200} height={800} /> */}
        <h1 className={styles.title}>Write for results, with less effort</h1>
        
        <form onSubmit={onSubmit}>
          <label for="sample" class="form-label">Enter your product and get a description... Instantly</label>
          <input 
            type="text" 
            name="sample"
            className="form-control" 
            placeholder="Enter your product name..." 
            value={sampleInput}
            onChange = {(e) => setSampleInput(e.target.value)}
          />
          <input type='submit' className={`btn btn-dark ${styles.buttonFont}`} value="Generate Descriptions"/>
        </form>
        <div className={styles.result}>{result}</div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
